---
title: "Tölvuverkefni 2"
author: "Enar Kornelius Leferink (ekl4@hi.is) og Sverrir Arnórsson (sva19@hi.is)"
date: "15/02/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(tidyr)
```

##1

###a)
Gögn lesin inn, Enar Kornelius notaði sinn afmælisdag til að búa til seed og þannig valið handahófskennt hverfi úr gefnum lista af hverfum. Bara íbúðareignir valdar.

```{r}
es <- read.table("https://notendur.hi.is/~ahj/husnaedi.txt", sep=";", header=T)
set.seed(2605)
hverfi <- sample(c(80,130,160,200),1)
es <- filter(es, matssvaedi%in%hverfi)
es <- filter(es, teg_eign=="Íbúðareign")
```
###b)

Stuðlarit af verði íbúðanna. Meðalverð er `r round(mean(es$nuvirdi), 3)` og dreifni er `r round(var(es$nuvirdi), 3)`.
```{r}
ggplot(data=es ,aes(nuvirdi)) + geom_histogram() + xlab("Verð")+ylab("Fjöldi")
```

###c)
```{r}
staerd1 <- replicate(10000, mean(sample(es$nuvirdi,10)))
staerd2 <- replicate(10000, mean(sample(es$nuvirdi,30)))
staerd3 <- replicate(10000, mean(sample(es$nuvirdi,100)))
staerd4 <- replicate(10000, mean(sample(es$nuvirdi,200)))
```
###d)
```{r}
hmr.es <- data.frame(staerd1, staerd2, staerd3, staerd4)
hmr.es.long <-gather(hmr.es, staerd, medaltal)
levels <- c(staerd1, staerd2, staerd3, staerd4)
hmr.es.long$staerd <- as.factor(hmr.es.long$staerd)
levels <- c(staerd1, staerd2, staerd3, staerd4)
labels <- c("Úrtak af stærð 10", "Úrtak af stærð 30", "Úrtak af stærð 100", "Úrtak af stærð 200")
hmr.es.long$staerd <-factor(hmr.es.long$staerd, levels=levels(hmr.es.long$staerd), labels=labels)



ggplot(hmr.es.long, aes(medaltal)) + geom_histogram() + facet_wrap(vars(staerd)) + xlab("Meðaltal") + ylab("Fjöldi")
```
###e)
```{r}
ggplot(hmr.es.long, aes(medaltal)) + geom_histogram() + facet_wrap(vars(staerd), scales = "free") + xlab("Meðaltal") + ylab("Fjöldi")
```
###f)
```{r}
tafla <- hmr.es.long %>% group_by(Úrtaksstærð = staerd)  %>% summarize(Meðaltal = mean(medaltal), Dreifni = var(medaltal))
knitr::kable(tafla)
```
###g

Það sem að sést í liðum e) og f) er að eftir því sem að úrtaksstærðin er aukin, því nær verður
