---
title: "Tölvuverkefni 1"
author: "Enar Kornelius Leferink (ekl4@hi.is) og Sverrir Arnórsson (sva19@hi.is)"
date: "1/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


## Hluti 1
### a)
```{r innlestur_gogn}
es <- read.table("husnaedi.txt", header=TRUE, sep=";", fileEncoding = "utf8")

```
### b)
```{r hverfi}
hverfi <- c(72,100,130)
es <- filter(es, matssvaedi%in%hverfi)
es$matssvaedi <- factor(es$matssvaedi, levels=c(72,100,130), labels=c("Hagar/Melar", "Laugarneshverfi/Vogar", "Grafarvogur"))

```
### c)
```{r tegund_gogn}
print(str(es))
```
Hér sést að allar breyturnar eru á réttu formi.

## Hluti 2
### a)
```{r eignir}
ggplot(data = es, aes(fill=teg_eign, matssvaedi, labels=TRUE)) + geom_bar(position="dodge") + xlab("Hverfi") +ylab("Fjöldi") + labs(fill = "Tegund eignar", title = "Fjöldi eigna eftir hverfum og tegundum")
```

### b)
```{r einbyli}
einbyli <- filter(es, teg_eign== "Einbýlishús")

fm = c(3,2,1)
i=1
for (hverfi in c("Hagar/Melar", "Laugarneshverfi/Vogar", "Grafarvogur")) {
  fm[i]<-mean(filter(einbyli, matssvaedi == hverfi)$ibm2)
  i = i+1
}
m2 <- data.frame(matssvaedi = c("Hagar/Melar", "Laugarneshverfi/Vogar", "Grafarvogur"), fm)

ggplot(data = m2, aes(x=matssvaedi,y=fm)) + geom_col() + xlab("Hverfi") + ylab("Fermetrar") + labs(title="Meðalfermetrafjöldi einbýlishúsa eftir hverfum")

```

### c)
```{r ibudir}
ibudir<-filter(es, teg_eign == "Íbúðareign")
ggplot(data=ibudir, aes(x=ibm2,y=nuvirdi)) + geom_point() + labs(x="Stærð [m^2]", y="Verð", title="Samband stærðar og verðs íbúðareigna")
```

## Hluti 3
### a)

Fjöldi mismunandi eigna eftir hverfum:

```{r fjoldi}
table(es$teg_eign,es$matssvaedi)
```

Hlutfall heildarfjölda eigna sem eru íbúðareignir:

```{r ib_vs_einbyli}
round(prop.table(table(es$teg_eign,es$matssvaedi),margin=2), 3)[2,]
```


## b)
Lýsistærðir fyrir einbýlishús:

```{r einbyli_stat1}

eTafla <- einbyli %>% group_by(Matssvæði = matssvaedi)  %>% summarise(Min = min(nuvirdi), IQ1 = quantile(nuvirdi, 0.25), Meðaltal = mean(nuvirdi), IQ3 = quantile(nuvirdi, 0.75),Max = max(nuvirdi), Miðgildi = median(nuvirdi), Staðalfrávik = sd(nuvirdi))

knitr::kable(eTafla, caption = "Lýsistærðir fyrir einbýlishús")
```

## c)

```{r litlaribudir}
litlaribudir <- filter(ibudir, ibm2>=50, ibm2<=60)
```

```{r litlareftirhverfum}
litlaribudir %>% group_by(Matssvæði = matssvaedi) %>% summarise(Fjöldi = n()) -> lTafla1
knitr::kable(lTafla1, caption="Fjöldi lítilla íbúða eftir hverfum")
```

```{r litlarlysandi}

lTafla2 <- litlaribudir %>% group_by(Matssvæði = matssvaedi)  %>% summarise( Fjöldi = n(), Meðaltal = mean(nuvirdi), Miðgildi = median(nuvirdi), Staðalfrávik = sd(nuvirdi))
knitr::kable(lTafla2, caption = "Lýsistærðir fyrir litlar íbúðir")
```

