---
title: "Tölvuverkefni 3"
author: "Enar Kornelius Leferink (ekl4@hi.is) og Sverrir Arnórsson (sva19@hi.is)"
date: "18/03/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
library(tidyverse)
install_github("AndySouth/rnaturalearthhires")
library(rnaturalearthhires)
library(ggplot2)
library(maps)
library(mapdata)
```

```{r}
r2d <-function(r)
{
    lat <- floor(r/100)
    lon <- (r - lat * 100) %% 50
    halfb <- (r - 100 * lat - lon)/100
    lon <-  - (lon + 0.5)
    lat <- lat + 60 + halfb + 0.25
    data.frame(lat = lat, lon = lon)
}
es<-read.csv("http://hi.is/~gunnar/LikTol/data98.csv")
reitir<-unique(es$reit)
x<-r2d(reitir)$lon
y<-r2d(reitir)$lat
plot(x,y,type='n')
text(x,y,as.character(reitir))
```
```{r}
es$hafsvaedi <- ifelse(r2d(es$reit)$lat<65 & r2d(es$reit)$lon < (-19), "SV", ifelse(r2d(es$reit)$lat>65 & r2d(es$reit)$lon <(-19), "NV", ifelse(r2d(es$reit)$lat>65 & r2d(es$reit)$lon >(-19), "NA","SA")))

es$kt2 <- ifelse(es$kt==1,"Ekki kynþroska","Kynþroska")
```
###b)
```{r}
tafla1 <- es %>% group_by( Hafssvæði = hafsvaedi, Kynþroski = kt2) %>% summarize(Fjöldi=n())
knitr::kable(tafla1)

knitr::kable(round(prop.table(table(es$kt2,es$hafsvaedi),2),2),row.names=TRUE)

ggplot(data=es, aes(fill=kt2, hafsvaedi)) + geom_bar(position="dodge")+ xlab("Hafsvæði") + ylab("Fjöldi") + labs(fill="Kynþroski")
```

```{r}
world <- sf::st_as_sf(rnaturalearthhires::countries10)
island <- world %>% filter(NAME=="Iceland")
island %>% ggplot(aes()) + geom_sf()

```

